#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=29gb,walltime=4:00:00
#PBS -N pRF

set -e
set -x

fsdir=$(jq -r .freesurfer config.json)

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $fsdir

