#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=120gb,walltime=24:00:00
#PBS -N pRF
#PBS -V

set -e
set -x

rm -rf $SUBJECTS_DIR/output #in case of multiple runs

output=$(jq -r .freesurfer config.json)
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

cp -R "$output" "$SUBJECTS_DIR"
subj_dir=$SUBJECTS_DIR

#time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.4 bash -c "SUBJECTS_DIR=$subj_dir && python -m neuropythy benson14_retinotopy $(basename $output) && for i in $SUBJECTS_DIR/output/mri/*benson14*; do mri_convert \$i \${i%.*}.nii.gz; done"

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.4 bash -c "SUBJECTS_DIR=$subj_dir && python -m neuropythy benson14_retinotopy $(basename $output)"

mkdir pRF_output
cp $SUBJECTS_DIR/output/surf/*benson14* pRF_output && cp $SUBJECTS_DIR/output/mri/*benson14* pRF_output
